---
title: TED、TED、TED
author: ''
date: '2018-09-20'
tags:
  - FRB
  - Fred
  - R
  - 金融
slug: ted
draft: yes
---

リーマン・ショックという経済危機から10年という節目を迎えるなか、米中貿易戦争が継続中です。また何か起こるのではないかという嫌な予感が漂うなかで、10年前を振り返る企画や記事が溢れています。

<!--more-->  

リーマン・ショックという経済危機から10年という節目を迎えるなか、米中貿易戦争が継続中です。また何か起こるのではないかという嫌な予感が漂うなかで、10年前を振り返る企画や記事が溢れています。

##### 犯人は誰だ

この危機の後、さまざまな原因についての説明がありましたが、正直よくわかりませんでした。欧米の金融機関が倒産しそうになった原因は、アメリカの住宅ローン、特に信用力が低い人向けのローン（サブ・プライム・ローン）を証券化した金融商品を販売し、購入していたからであったという説明を聞いても、全く理解ができませんでした。返済に不安がある人たちにローンを貸し出して、そのローンをプールに入れて、かき混ぜて、小分けにして売り出しましたという説明なのです。そんな金融商品を世界中の金融機関が買いあさったのが不思議なのですが、一応そこには（振り返ってバブルだったとはいえ）なんらかの裏付けがあったはずです。その裏付けになったものはなんだったのかが、気になりました。もとよりリスクのない金融商品などないわけですが、その**リスクを◯◯しているので安全です**というフレーズがないとここまで売れないはずです。

WiredというIT関係のWebで[RECIPE FOR DISASTER: THE FORMULA THAT KILLED WALL STREET（大惨事の処方箋：ウォール・ストリートを殺した数式）](https://www.wired.com/2009/02/wp-quant/)という記事（2009年2月）に、安全の根拠らしいものがありました。中国からカナダへ留学し、年金数理の修士号と統計の博士号をとったDavid X Liという中国人のお話です。金融界の悩みの一つが、ローンAとローンB、C、D・・を一つのプールに入れた商品を販売しようとした時、ローンAが債務不履行（デフォルト）となりそうな時に他のローンへの影響（相関関係）を計測する確かな方法がないことでした。これに対して、Liの2000年の論文にある`Gaussian copula function`を使うとローンの相関関係が簡便に計算できるということで 

##### 知ってる人たちはいた

キナ臭い感じがしていた頃、”Caluculated Risk"というブログが話題となっていました。読んでみましたが、アメリカ国内の住宅ローンの仕組みを英語で説明されてもよく分からないというのが正直な印象でした。しばらく読まないうちに、



##### 正しい処方箋は



もちろん、金融危機の影響を抑えるべく、政府、金融規制当局が危機の前後に何を考え、どう行動したのかを追いかけた本や高官たちの回顧録はかなり真面目に読みました。マイケル・ルイスの[Big Short（世紀の空売り）](https://www.amazon.co.jp/%E4%B8%96%E7%B4%80%E3%81%AE%E7%A9%BA%E5%A3%B2%E3%82%8A%E2%80%95%E4%B8%96%E7%95%8C%E7%B5%8C%E6%B8%88%E3%81%AE%E7%A0%B4%E7%B6%BB%E3%81%AB%E8%B3%AD%E3%81%91%E3%81%9F%E7%94%B7%E3%81%9F%E3%81%A1-%E6%96%87%E6%98%A5%E6%96%87%E5%BA%AB-%E3%83%9E%E3%82%A4%E3%82%B1%E3%83%AB%E3%83%BB%E3%83%AB%E3%82%A4%E3%82%B9/dp/4167651866/ref=sr_1_2?ie=UTF8&qid=1538379912&sr=8-2&keywords=%E4%B8%96%E7%B4%80%E3%81%AE%E7%A9%BA%E5%A3%B2%E3%82%8A)とその映画化などはこの危機を裏側から見ることができて面白かったのですが、今一つ何かが足りないと感じていました。



##### Tedって誰だ？

```{r message=FALSE, warning=FALSE}
library(quantmod)
getSymbols("TEDRATE", src = "FRED")
plot.xts(TEDRATE)
```







George W. Bush Hails Ben Bernanke–and Comes Clean(白状する) on the TED Spread
